### ISSUE TITLE
Can't work in windows 10+Anaconda (python 3.7) environment.

### ISSUE THREAD

**Issue by Jiuhaoqiu** [chennnnnyize/Renewables_Scenario_Gen_GAN#2]
Thanks for providing this code, but I encountered some problems when compiling.  I tried to compile in windows 10+anaconda (python 3.7) environment. But the compilation shows an error：
  File "G:/PYTHONcode/Renewables_Scenario_Gen_GAN-master/datasets/train.py", line 155, in <module>
    csvfile=file('%s.csv' %iterations, 'wb')
NameError: name 'file' is not defined
   It seems that  python 3.7 remove the file function,but when I replace 'file' to 'open',It turns to another error:
  File "G:/PYTHONcode/Renewables_Scenario_Gen_GAN-master/datasets/train.py", line 157, in <module>
    writer.writerows(generated_samples)
TypeError: a bytes-like object is required, not 'str'
Can you provide some help?

**Comment by amen183** [comment]
delete them, then the code can be  ran.

**Comment by Jiuhaoqiu** [comment]
> 删除它们，然后可以运行代码。
Thanks for responding so quickly.
When I replace all the 'file' to 'open' and all the  'wb' to 'w' ,it can run now,but it spend a lot of time.
It take me an hour to literations 6000 itmes,this code is still running now,(The CPU configuration of my laptop is i5).Do you have any suggestions for calculating the time?

**Comment by amen183** [comment]
Sorry about that, I just know that GPU can accelerate the calculation.  I use a server to run the code, it only take few minutes.  If you want a fast speed, change your laptop.

**Comment by Jiuhaoqiu** [comment]
Thanks for the reply, a pleasant conversation.

**Comment by chennnnnyize** [comment]
Hi Jiuhao,

I believe you shall resolve the error so I will close the issue. Basically there is a version conflict on the saving file code between Python 2 and Python 3. Try to change wb to w will solve the problem. GPU will help accelerate the code.

**Comment by jsga** [comment]
Changing that line to this one solves the version conflict between Python 2 and 3:
`csvfile=open('%s.csv' %iterations, 'w')`
