### ISSUE TITLE
The Wasserstein distance did not converge.

### ISSUE THREAD

**Issue by Jiuhaoqiu** [chennnnnyize/Renewables_Scenario_Gen_GAN#3]
![aaa](https://user-images.githubusercontent.com/46060854/50537140-41000b80-0b97-11e9-85f6-c5a250933d6e.png)
![bbb](https://user-images.githubusercontent.com/46060854/50537143-4bbaa080-0b97-11e9-81fd-b68c7eeeca52.png)

    I used the server to get the two images, where the Wasserstein distance did not converge. Is this because the data on github is not the same as the data in the paper?D(X)/D(G(Z)) is also different from the results in the paper.

**Comment by Jiuhaoqiu** [comment]
> 您使用的是哪种数据，太阳能还是风能？确保代码读取正确的标签。
I use the wind data.
    I am very interested in Figure 8 (picture below) in the paper, because I am doing some stochastic programming  related projects, I need to generate some scenarios, what advice do you have? it would be better if you can provide some code. Anyway, thanks to the code provided on github

![zhang8-2794541-small](https://user-images.githubusercontent.com/46060854/50538027-8e827580-0ba3-11e9-9e2a-6b5c7ca8f94e.gif)

**Comment by amen183** [comment]
I am not the auther, and my research direction is not related. If you want to get the figure, the code is enough.

**Comment by Jiuhaoqiu** [comment]
> 我不是作者，我的研究方向也不相关。如果你想得到数字，代码就足够了。
OK，Thank you for your enthusiasm.

**Comment by cby007** [comment]
> I have the same problem, have you solved it?

**Comment by chennnnnyize** [comment]
> > I have the same problem, have you solved it?

We uploaded the same dataset as is shown in the paper. Please check the training procedure, and see if the generated scenarios are valid. Thanks.

**Comment by wyhzz97** [comment]
> ![aaa](https://user-images.githubusercontent.com/46060854/50537140-41000b80-0b97-11e9-85f6-c5a250933d6e.png) ![bbb](https://user-images.githubusercontent.com/46060854/50537143-4bbaa080-0b97-11e9-81fd-b68c7eeeca52.png)
> 
> ```
> I used the server to get the two images, where the Wasserstein distance did not converge. Is this because the data on github is not the same as the data in the paper?D(X)/D(G(Z)) is also different from the results in the paper.
> ```

I get the same images as you, and the Wasserstein distance did not converge,have you solved it?

**Comment by ruichenhaoandlittlecap** [comment]
> I am not the auther, and my research direction is not related. If you want to get the figure, the code is enough.

Sorry to bother you, I want to know whether you get the right figure using the code
